# Generated by Django 4.2.16 on 2024-11-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_photo_orderphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='photo',
            field=models.ImageField(default=None, null=True, upload_to='image/', verbose_name='Изображение категории'),
        ),
        migrations.DeleteModel(
            name='OrderPhoto',
        ),
    ]
