# Generated by Django 4.2.16 on 2024-12-06 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activation_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_activated',
        ),
    ]
