# Generated by Django 4.2.16 on 2024-12-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_activated',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Прошел активацию?'),
        ),
    ]
